behaviors:
  TurretShoot:
    trainer_type: sac
    hyperparameters:
      buffer_size: 500000
      batch_size: 128
      learning_rate: 0.0003
      tau: 0.005
      steps_per_update: 10
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 10000
